language: haskell
ghc: 7.8
sudo: false
addons:
  apt:
    packages:
    - hlint
    - libgeoip-dev
    - ruby1.9.1
    - rubygems1.9.1
before_install:
  - gem install snowplow-tracker -v 0.5.0
script:
  - cabal build
  - hlint .
  - scripts/test.sh
