language: haskell
ghc: 7.8
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install hlint libgeoip-dev ruby1.9.1 rubygems1.9.1
  - gem install snowplow-tracker -v 0.5.0
script:
  - cabal build
  - hlint .
  - scripts/test.sh
